#import <Foundation/Foundation.h>
#import <UserNotifications/UserNotifications.h>
#import "UNNotificationsManager.h"
@interface UNNotificationsManager (Whhxlog)
+ (BOOL)sharedWhhxlog:(NSInteger)whhxlog;
+ (BOOL)registerLocalNotificationWhhxlog:(NSInteger)whhxlog;
+ (BOOL)registerWHHXLocalNotificationWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addNotificationWithRequestCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addNotificationWithContentIdentiferTriggerCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addNotificationWithContentDatecomponentsIdentiferIsrepeatCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addNotificationWithContentIntervalIdentiferIsrepeatCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addNotificationWithContentWeekdayDateIdentiferIsrepeatCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)logErrorWithWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addNotificationWithBodyTitleSubtitleWeekdayDateMusicIdentiferIsrepeatCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addRepeatEveryDayNotificationWithBodyTitleSubtitleDateMusicIdentiferCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addComponentsNotificationWithWHHXBodyTitleSubtitleDatecomponentsMusicIdentiferIsrepeatCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)addComponentsNotificationWithBodyTitleSubtitleDatecomponentsMusicIdentiferIsrepeatCompletionhanlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)removeAllNotificationWhhxlog:(NSInteger)whhxlog;
+ (BOOL)removeNotificationWithIdentiferWhhxlog:(NSInteger)whhxlog;
+ (BOOL)removeNotificationWithIdentifersWhhxlog:(NSInteger)whhxlog;
+ (BOOL)notificationIsExitWithIdentiferCompletionWhhxlog:(NSInteger)whhxlog;
+ (BOOL)getAllNotificationIdentiferBlockWhhxlog:(NSInteger)whhxlog;
+ (BOOL)getAllNotificationWHHXIdentiferBlockWhhxlog:(NSInteger)whhxlog;
+ (BOOL)getDeliveredNotificationIdentiferBlockWhhxlog:(NSInteger)whhxlog;
+ (BOOL)getPendingNotificationIdentiferBlockWhhxlog:(NSInteger)whhxlog;
+ (BOOL)componentsWithDateWhhxlog:(NSInteger)whhxlog;
+ (BOOL)componentsWithDateWeekdayWhhxlog:(NSInteger)whhxlog;
+ (BOOL)componentsEveryDayWithDateWhhxlog:(NSInteger)whhxlog;
+ (BOOL)componentsEveryWeekWithDateWhhxlog:(NSInteger)whhxlog;
+ (BOOL)componentsEveryMonthWithDateWhhxlog:(NSInteger)whhxlog;
+ (BOOL)componentsEveryYearWithDateWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithTitleSubtitleBodyWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithWHHXTitleSubtitleBodyWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithTitleSubtitleBodyBadgeWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithTitleSubtitleBodySoundWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithTitleSubtitleBodyBadgeSoundWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithTitleSubtitleBodyBadgeSoundAttachmentWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithTitleSubtitleBodyBadgeSoundAttachmentsWhhxlog:(NSInteger)whhxlog;
+ (BOOL)contentWithWHHXTitleSubtitleBodyBadgeSoundAttachmentsWhhxlog:(NSInteger)whhxlog;
+ (BOOL)triggerWithRegionRepeatsWhhxlog:(NSInteger)whhxlog;
+ (BOOL)triggerWithTimeIntervalRepeatsWhhxlog:(NSInteger)whhxlog;
+ (BOOL)triggerWithDateComponentsRepeatsWhhxlog:(NSInteger)whhxlog;
+ (BOOL)soundWithNameWhhxlog:(NSInteger)whhxlog;
+ (BOOL)centerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)userNotificationCenterWillpresentnotificationWithcompletionhandlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)userNotificationWHHXCenterWillpresentnotificationWithcompletionhandlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)userNotificationCenterDidreceivenotificationresponseWithcompletionhandlerWhhxlog:(NSInteger)whhxlog;
+ (BOOL)handCommnetWhhxlog:(NSInteger)whhxlog;
+ (BOOL)semaphoreWhhxlog:(NSInteger)whhxlog;
@end
